import type { Agent, Blueprint } from "@/lib/blueprint/schema";
import { allBlocks } from "@/lib/blueprint";
import { MEMORY_LABEL, PERMISSION_LABEL, SUPERVISION_LABEL } from "@/lib/blueprint/describe";

/** YAML scalar: quote when needed. */
export function y(v: string | number | boolean): string {
  if (typeof v !== "string") return String(v);
  if (/^[A-Za-z0-9_.\-/ ]+$/.test(v) && !/^(yes|no|true|false|null|on|off)$/i.test(v) && !/^[\d.]+$/.test(v) && !v.includes(": ") && v.trim() === v) return v;
  return JSON.stringify(v);
}

export function agentYaml(agent: Agent, bp: Blueprint): string {
  const conn = (id: string) => bp.connections.find((c) => c.id === id);
  const lines = [
    "# GitAgent spec, generated by Architect 2.0. This file is the source of truth for this agent.",
    `id: ${y(agent.id)}`,
    `name: ${y(agent.name)}`,
    `role: ${y(agent.role)}`,
    `model: ${y(agent.cost.model)}`,
    `framework: ${agent.framework}`,
    `supervision: ${agent.supervision}   # ${SUPERVISION_LABEL[agent.supervision].label}`,
    "memory:",
    `  scope: ${agent.memory.scope}`,
    `  retention_days: ${agent.memory.retentionDays}`,
    `triggers: [${agent.triggers.join(", ")}]`,
    "tools:",
    ...agent.tools.flatMap((t) => [
      `  - id: ${t.id}`,
      `    connection: ${t.connectionId}${conn(t.connectionId) ? `   # ${conn(t.connectionId)!.name}` : ""}`,
      `    access: ${t.access}`,
      `    permission: ${t.permission}   # ${PERMISSION_LABEL[t.permission]}`,
    ]),
    ...(agent.knowledge.length ? ["knowledge:", ...agent.knowledge.map((k) => `  - { source: ${k.source}, ref: ${y(k.ref)} }`)] : ["knowledge: []"]),
    "rehearsals:",
    ...agent.rehearsals.flatMap((r) => [`  - name: ${y(r.name)}`, `    input: ${y(r.input)}`, `    expect: ${y(r.expect)}`]),
    "budget:",
    `  credits_per_run: ${agent.cost.creditsPerRun}`,
    "",
  ];
  return lines.join("\n");
}

export function soulMd(agent: Agent): string {
  return `# ${agent.name}

> ${agent.role}

${agent.plain}

## Job description

${agent.jobDescription}

## Memory

${MEMORY_LABEL[agent.memory.scope]} (kept ${agent.memory.retentionDays} days).
`;
}

export function rulesMd(agent: Agent, bp: Blueprint): string {
  const name = (id: string) => bp.connections.find((c) => c.id === id)?.name ?? id;
  return `# Rules for ${agent.name}

${agent.rules.map((r, i) => `${i + 1}. ${r}`).join("\n")}

## What it may do

| Tool | Where | Access | Permission |
| --- | --- | --- | --- |
${agent.tools.map((t) => `| ${t.name} | ${name(t.connectionId)} | ${t.access} | ${PERMISSION_LABEL[t.permission]} |`).join("\n")}

Supervision: **${SUPERVISION_LABEL[agent.supervision].label}**: ${SUPERVISION_LABEL[agent.supervision].plain}
`;
}

export function dutiesMd(agent: Agent, bp: Blueprint): string {
  const screens = bp.screens.filter((s) =>
    allBlocks(s).some((b) => (b.type === "chat" && b.agentId === a(agent)) || (b.type === "detail" && b.actions.some((x) => x.action.kind === "agent" && x.action.agentId === agent.id))),
  );
  return `# Duties

## When it runs
${agent.triggers.map((t) => `- ${t === "on_create" ? "When a new record arrives" : t === "chat" ? "When someone talks to it" : t === "schedule" ? "On a schedule" : "When someone presses a button"}`).join("\n")}

## Where people meet it
${screens.length ? screens.map((s) => `- ${s.title}`).join("\n") : "- Only through the API"}

## Rehearsals (must pass before going live)
${agent.rehearsals.map((r) => `- [${r.history.length && r.history[r.history.length - 1].pass ? "x" : " "}] **${r.name}**: ${r.input} → _${r.expect}_`).join("\n")}
`;
}

const a = (agent: Agent) => agent.id;
