import type { Block, Blueprint, Entity, Screen } from "@/lib/blueprint/schema";
import { FRAMEWORKS } from "./frameworks";
import { agentYaml, dutiesMd, rulesMd, soulMd } from "./agentFiles";
import type { GeneratedFile } from "./types";

const kebab = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const pascal = (s: string) => s.replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, c: string) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, "");
const camel = (s: string) => {
  const p = pascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
};
const js = (v: unknown) => JSON.stringify(v);

export function envKey(name: string) {
  return name.toUpperCase().replace(/\(.*?\)/g, "").replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "");
}

function sqlType(t: Entity["fields"][number]["type"]) {
  return t === "money" ? "numeric(12,2)" : t === "number" ? "numeric" : t === "date" ? "date" : t === "boolean" ? "boolean" : "text";
}

export function schemaSql(bp: Blueprint): string {
  return (
    `-- Generated by Prod AI from “${bp.meta.name}”. Row-level security is on for every table.\n\n` +
    bp.entities
      .map((e) => {
        const table = kebab(e.plural).replace(/-/g, "_");
        return [
          `create table ${table} (`,
          `  id uuid primary key default gen_random_uuid(),`,
          ...e.fields.map((f) => `  ${f.name} ${sqlType(f.type)}${f.type === "enum" && f.options ? ` check (${f.name} in (${f.options.map((o) => `'${o.replace(/'/g, "''")}'`).join(", ")}))` : ""},`),
          `  team_id uuid not null references teams(id),`,
          `  created_at timestamptz not null default now()`,
          `);`,
          `alter table ${table} enable row level security;`,
          `create policy "team members" on ${table} using (team_id in (select team_id from memberships where user_id = auth.uid()));`,
        ].join("\n");
      })
      .join("\n\n") +
    "\n"
  );
}

function blockJsx(b: Block, bp: Blueprint, indent: string): string {
  const entity = "entityId" in b && b.entityId ? bp.entities.find((e) => e.id === b.entityId) : undefined;
  const rows = entity ? camel(entity.plural) : "[]";
  const nav = (a?: { kind: string; screenId?: string }) => (a?.kind === "navigate" ? bp.screens.find((s) => s.id === a.screenId)?.slug : undefined);
  switch (b.type) {
    case "kpis":
      return `${indent}<Kpis items={${js(b.items.map(({ label, value, delta }) => ({ label, value, delta })))}} />`;
    case "table":
      return `${indent}<DataTable\n${indent}  title=${js(b.title ?? entity?.plural ?? "")}\n${indent}  rows={${rows}}\n${indent}  columns={${js(b.columns)}}\n${indent}  filters={${js(b.filters)}}${nav(b.rowAction) ? `\n${indent}  rowHref={(row) => \`/${nav(b.rowAction)}/\${row.id}\`}` : ""}\n${indent}/>`;
    case "list":
      return `${indent}<RecordList title=${js(b.title ?? "")} rows={${rows}} titleField=${js(b.titleField)}${b.subtitleField ? ` subtitleField=${js(b.subtitleField)}` : ""}${b.badgeField ? ` badgeField=${js(b.badgeField)}` : ""} />`;
    case "detail":
      return `${indent}<RecordView record={${entity ? camel(entity.name) : "record"}} fields={${js(b.fields)}}>\n${b.actions.map((a) => `${indent}  <ActionButton variant=${js(a.variant)} ${a.action.kind === "agent" ? `agent=${js(a.action.agentId)} prompt=${js(a.action.prompt)}` : `onClick={() => toast(${js(a.action.kind === "toast" ? a.action.message : "")})}`}>${a.label}</ActionButton>`).join("\n")}\n${indent}</RecordView>`;
    case "form":
      return `${indent}<AgentForm\n${indent}  title=${js(b.title)}\n${indent}  fields={${js(b.fields.map(({ name, label, kind, options, required }) => ({ name, label, kind, options, required })))}}\n${indent}  submitLabel=${js(b.submitLabel)}\n${indent}  action={${entity ? `create${pascal(entity.name)}` : "submit"}}\n${indent}/>`;
    case "chat":
      return `${indent}<AgentChat agent=${js(b.agentId)} title=${js(b.title ?? "")} placeholder=${js(b.placeholder)} starters={${js(b.starters)}} />`;
    case "timeline":
      return `${indent}<Timeline items={${js(b.items)}} />`;
    case "text":
      return `${indent}<Note title=${js(b.title ?? "")}>{${js(b.markdown)}}</Note>`;
    case "actions":
      return `${indent}<Actions>\n${b.buttons.map((x) => `${indent}  <ActionButton variant=${js(x.variant)}>${x.label}</ActionButton>`).join("\n")}\n${indent}</Actions>`;
  }
}

export function screenPage(s: Screen, bp: Blueprint): string {
  const blocks = [...s.regions.main, ...s.regions.side];
  const used = new Set<string>(["Screen"]);
  const names: Record<Block["type"], string> = { kpis: "Kpis", table: "DataTable", list: "RecordList", detail: "RecordView", form: "AgentForm", chat: "AgentChat", timeline: "Timeline", text: "Note", actions: "Actions" };
  blocks.forEach((b) => {
    used.add(names[b.type]);
    if (b.type === "detail" || b.type === "actions") used.add("ActionButton");
  });
  const entities = [...new Set(blocks.map((b) => ("entityId" in b ? b.entityId : undefined)).filter(Boolean) as string[])]
    .map((id) => bp.entities.find((e) => e.id === id)!)
    .filter(Boolean);
  const imports = entities.map((e) => `import { ${camel(e.plural)}, ${camel(e.name)}${blocks.some((b) => b.type === "form" && b.entityId === e.id) ? `, create${pascal(e.name)}` : ""} } from "@/lib/data/${e.id}";`);
  return `// ${s.title}: ${s.purpose}
// Generated by Prod AI. Safe to edit: changes sync back into the blueprint.
import { ${[...used].sort().join(", ")} } from "@/components/blocks";
${imports.join("\n")}${blocks.some((b) => b.type === "detail" && b.actions.some((a) => a.action.kind === "toast")) ? '\nimport { toast } from "sonner";' : ""}

export default async function ${pascal(s.title)}Page() {
  return (
    <Screen title=${js(s.title)} layout=${js(s.layout)} audience=${js(s.audience)}>
      <Screen.Main>
${s.regions.main.map((b) => blockJsx(b, bp, "        ")).join("\n")}
      </Screen.Main>${s.regions.side.length ? `\n      <Screen.Side>\n${s.regions.side.map((b) => blockJsx(b, bp, "        ")).join("\n")}\n      </Screen.Side>` : ""}
    </Screen>
  );
}
`;
}

export function entityModule(e: Entity): string {
  const tsType = (t: string) => (t === "number" || t === "money" ? "number" : t === "boolean" ? "boolean" : "string");
  return `// ${e.plural}: ${e.plain}
import { db } from "@/lib/db";

export type ${pascal(e.name)} = {
  id: string;
${e.fields.map((f) => `  ${f.name}: ${f.type === "enum" && f.options ? f.options.map((o) => JSON.stringify(o)).join(" | ") : tsType(f.type)};`).join("\n")}
};

export const ${camel(e.plural)} = db.table<${pascal(e.name)}>(${js(kebab(e.plural).replace(/-/g, "_"))});
export const ${camel(e.name)} = ${camel(e.plural)}.current;
export const create${pascal(e.name)} = ${camel(e.plural)}.insert;

// Sample records used in the Test version (never shipped to Live)
export const sample${pascal(e.plural)}: Partial<${pascal(e.name)}>[] = ${JSON.stringify(e.sample, null, 2)};
`;
}

export function envExample(bp: Blueprint): string {
  const lines = ["# Keys & passwords: never commit real values.", "SUPABASE_URL=", "SUPABASE_PUBLISHABLE_KEY=", "ANTHROPIC_API_KEY="];
  for (const c of bp.connections) {
    if (c.kind === "database") continue;
    if (c.auth === "api_key") lines.push(`${envKey(c.name)}_API_KEY=   # ${c.name}${c.status === "missing" ? " (missing)" : ""}`);
    if (c.auth === "oauth") lines.push(`${envKey(c.name)}_CLIENT_ID=\n${envKey(c.name)}_CLIENT_SECRET=`);
  }
  return lines.join("\n") + "\n";
}

export function generateFiles(bp: Blueprint): GeneratedFile[] {
  const name = kebab(bp.meta.name);
  const files: GeneratedFile[] = [];
  const frameworks = [...new Set(bp.agents.map((a) => a.framework))];

  files.push({
    path: "README.md",
    lang: "md",
    objectRef: { type: "brief", id: "meta" },
    content: `# ${bp.meta.name}

${bp.meta.tagline}

${bp.meta.plain}

## Agents

| Agent | Role | Framework | Supervision |
| --- | --- | --- | --- |
${bp.agents.map((a) => `| ${a.name} | ${a.role} | ${FRAMEWORKS[a.framework].label} | ${a.supervision} |`).join("\n")}

## Run it

\`\`\`sh
cp .env.example .env.local   # add your keys
npm install
npm run dev                  # app on :3000
npm run rehearse             # replays every agent's rehearsals
\`\`\`

Built with Prod AI. \`blueprint.json\` is the source of truth; edit code or blueprint, both stay in sync.
`,
  });
  files.push({
    path: "package.json",
    lang: "json",
    content: JSON.stringify(
      {
        name,
        private: true,
        scripts: { dev: "next dev", build: "next build", start: "next start", rehearse: "prodai rehearse", sync: "prodai sync" },
        dependencies: { next: "^16.3.0", react: "^19.2.0", "@supabase/ssr": "^0.12.0", ai: "^7.0.0", "@ai-sdk/anthropic": "^4.0.0", "@prodai/blocks": "^2.0.0", ...(frameworks.includes("mastra") ? { "@mastra/core": "^1.0.0" } : {}) },
        devDependencies: { "@prodai/cli": "^2.0.0", typescript: "^5.9.0" },
      },
      null,
      2,
    ) + "\n",
  });
  files.push({ path: ".env.example", lang: "env", content: envExample(bp) });
  files.push({
    path: "docker-compose.yml",
    lang: "yaml",
    content: `# Run the whole app inside your own VPC. Prod Cloud is optional.
services:
  web:
    build: .
    ports: ["3000:3000"]
    env_file: .env.local
    depends_on: [db, agents]
  agents:
    image: ghcr.io/prodai/agent-runtime:2
    environment:
      AGENTS_DIR: /agents
      REGION: ${bp.meta.region}
    volumes: ["./agents:/agents:ro"]
    env_file: .env.local
  db:
    image: supabase/postgres:17.6.1
    volumes: ["pgdata:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?set in .env.local}
volumes:
  pgdata: {}
`,
  });
  files.push({ path: "blueprint.json", lang: "json", objectRef: { type: "brief", id: "meta" }, content: JSON.stringify({ ...bp, estimate: undefined }, null, 2) + "\n" });
  files.push({
    path: "app/layout.tsx",
    lang: "tsx",
    content: `import { AppShell } from "@/components/blocks";
import { requireSignIn } from "@/lib/auth";

export const metadata = { title: ${js(bp.meta.name)}, description: ${js(bp.meta.tagline)} };

const nav = ${JSON.stringify(bp.screens.map((s) => ({ href: `/${s.slug}`, label: s.title, icon: s.icon, audience: s.audience })), null, 2).replace(/\n/g, "\n")};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  ${bp.meta.auth.enabled ? `await requireSignIn({ providers: ${js(bp.meta.auth.providers)} });` : "// Sign-in is off: anyone with the link can open this app."}
  return (
    <html lang="en">
      <body>
        <AppShell name=${js(bp.meta.name)} nav={nav} theme={${js(bp.meta.theme)}}>{children}</AppShell>
      </body>
    </html>
  );
}
`,
  });
  files.push({ path: "components/blocks/index.ts", lang: "ts", content: `// Prod AI's block library. Every block is a normal React component. Swap any of them for your own.\nexport * from "@prodai/blocks";\n` });
  files.push({ path: "supabase/schema.sql", lang: "sql", content: schemaSql(bp) });
  files.push({
    path: ".github/workflows/rehearsals.yml",
    lang: "yaml",
    content: `name: Rehearsals
on: [pull_request]
jobs:
  rehearse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      - run: npm ci
      - run: npx prodai rehearse --fail-under 0.9   # blocks the merge if agents regress
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
`,
  });

  for (const s of bp.screens) files.push({ path: `app/(app)/${s.slug}/page.tsx`, lang: "tsx", content: screenPage(s, bp), objectRef: { type: "screen", id: s.id } });
  for (const e of bp.entities) files.push({ path: `lib/data/${e.id}.ts`, lang: "ts", content: entityModule(e), objectRef: { type: "entity", id: e.id } });
  for (const a of bp.agents) {
    const fw = FRAMEWORKS[a.framework];
    const ref = { type: "agent" as const, id: a.id };
    files.push({ path: `agents/${a.id}/agent.yaml`, lang: "yaml", content: agentYaml(a, bp), objectRef: ref });
    files.push({ path: `agents/${a.id}/SOUL.md`, lang: "md", content: soulMd(a), objectRef: ref });
    files.push({ path: `agents/${a.id}/RULES.md`, lang: "md", content: rulesMd(a, bp), objectRef: ref });
    files.push({ path: `agents/${a.id}/DUTIES.md`, lang: "md", content: dutiesMd(a, bp), objectRef: ref });
    files.push({ path: `agents/${a.id}/${fw.fileName(a)}`, lang: fw.language === "python" ? "py" : "ts", content: fw.render(a, bp), objectRef: ref });
  }
  return files;
}

export function filesFor(bp: Blueprint, ref: { type: string; id: string }): GeneratedFile[] {
  return generateFiles(bp).filter((f) => f.objectRef && f.objectRef.type === ref.type && f.objectRef.id === ref.id);
}
