import type { Agent, Block, Blueprint, Entity, Screen } from "@/lib/blueprint/schema";
import { houseRulePolicy, isInfraPath, ruleBlocking } from "@/lib/import/house-rules";
import { FRAMEWORKS } from "./frameworks";
import { agentYaml, dutiesMd, rulesMd, soulMd } from "./agentFiles";
import type { GeneratedFile } from "./types";

const kebab = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const pascal = (s: string) => s.replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, c: string) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, "");
const camel = (s: string) => {
  const p = pascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
};
const js = (v: unknown) => JSON.stringify(v);

export function envKey(name: string) {
  return name.toUpperCase().replace(/\(.*?\)/g, "").replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "");
}

function sqlType(t: Entity["fields"][number]["type"]) {
  return t === "money" ? "numeric(12,2)" : t === "number" ? "numeric" : t === "date" ? "date" : t === "boolean" ? "boolean" : "text";
}

export function schemaSql(bp: Blueprint): string {
  return (
    `-- Generated by Prod AI from “${bp.meta.name}”. Row-level security is on for every table.\n\n` +
    bp.entities
      .map((e) => {
        const table = kebab(e.plural).replace(/-/g, "_");
        return [
          `create table ${table} (`,
          `  id uuid primary key default gen_random_uuid(),`,
          ...e.fields.map((f) => `  ${f.name} ${sqlType(f.type)}${f.type === "enum" && f.options ? ` check (${f.name} in (${f.options.map((o) => `'${o.replace(/'/g, "''")}'`).join(", ")}))` : ""},`),
          `  team_id uuid not null references teams(id),`,
          `  created_at timestamptz not null default now()`,
          `);`,
          `alter table ${table} enable row level security;`,
          `create policy "team members" on ${table} using (team_id in (select team_id from memberships where user_id = auth.uid()));`,
        ].join("\n");
      })
      .join("\n\n") +
    "\n"
  );
}

function blockJsx(b: Block, bp: Blueprint, indent: string): string {
  const entity = "entityId" in b && b.entityId ? bp.entities.find((e) => e.id === b.entityId) : undefined;
  const rows = entity ? camel(entity.plural) : "[]";
  const nav = (a?: { kind: string; screenId?: string }) => (a?.kind === "navigate" ? bp.screens.find((s) => s.id === a.screenId)?.slug : undefined);
  switch (b.type) {
    case "kpis":
      return `${indent}<Kpis items={${js(b.items.map(({ label, value, delta }) => ({ label, value, delta })))}} />`;
    case "table":
      return `${indent}<DataTable\n${indent}  title=${js(b.title ?? entity?.plural ?? "")}\n${indent}  rows={${rows}}\n${indent}  columns={${js(b.columns)}}\n${indent}  filters={${js(b.filters)}}${b.sort ? `\n${indent}  sort={${js(b.sort)}}` : ""}${nav(b.rowAction) ? `\n${indent}  rowHref={(row) => \`/${nav(b.rowAction)}/\${row.id}\`}` : ""}\n${indent}/>`;
    case "list":
      return `${indent}<RecordList title=${js(b.title ?? "")} rows={${rows}} titleField=${js(b.titleField)}${b.subtitleField ? ` subtitleField=${js(b.subtitleField)}` : ""}${b.badgeField ? ` badgeField=${js(b.badgeField)}` : ""} />`;
    case "detail":
      return `${indent}<RecordView record={${entity ? camel(entity.name) : "record"}} fields={${js(b.fields)}}>\n${b.actions.map((a) => `${indent}  <ActionButton variant=${js(a.variant)} ${a.action.kind === "agent" ? `agent=${js(a.action.agentId)} prompt=${js(a.action.prompt)}` : `onClick={() => toast(${js(a.action.kind === "toast" ? a.action.message : "")})}`}>${a.label}</ActionButton>`).join("\n")}\n${indent}</RecordView>`;
    case "form":
      return `${indent}<AgentForm\n${indent}  title=${js(b.title)}\n${indent}  fields={${js(b.fields.map(({ name, label, kind, options, required }) => ({ name, label, kind, options, required })))}}\n${indent}  submitLabel=${js(b.submitLabel)}\n${indent}  action={${entity ? `create${pascal(entity.name)}` : "submit"}}\n${indent}/>`;
    case "chat":
      return `${indent}<AgentChat agent=${js(b.agentId)} title=${js(b.title ?? "")} placeholder=${js(b.placeholder)} starters={${js(b.starters)}} />`;
    case "timeline":
      return `${indent}<Timeline items={${js(b.items)}} />`;
    case "text":
      return `${indent}<Note title=${js(b.title ?? "")}>{${js(b.markdown)}}</Note>`;
    case "actions":
      return `${indent}<Actions>\n${b.buttons.map((x) => `${indent}  <ActionButton variant=${js(x.variant)}>${x.label}</ActionButton>`).join("\n")}\n${indent}</Actions>`;
  }
}

export function screenPage(s: Screen, bp: Blueprint): string {
  const blocks = [...s.regions.main, ...s.regions.side];
  const used = new Set<string>(["Screen"]);
  const names: Record<Block["type"], string> = { kpis: "Kpis", table: "DataTable", list: "RecordList", detail: "RecordView", form: "AgentForm", chat: "AgentChat", timeline: "Timeline", text: "Note", actions: "Actions" };
  blocks.forEach((b) => {
    used.add(names[b.type]);
    if (b.type === "detail" || b.type === "actions") used.add("ActionButton");
  });
  const entities = [...new Set(blocks.map((b) => ("entityId" in b ? b.entityId : undefined)).filter(Boolean) as string[])]
    .map((id) => bp.entities.find((e) => e.id === id)!)
    .filter(Boolean);
  const imports = entities.map((e) => `import { ${camel(e.plural)}, ${camel(e.name)}${blocks.some((b) => b.type === "form" && b.entityId === e.id) ? `, create${pascal(e.name)}` : ""} } from "@/lib/data/${e.id}";`);
  return `// ${s.title}: ${s.purpose}
// Generated by Prod AI. Safe to edit: changes sync back into the blueprint.
import { ${[...used].sort().join(", ")} } from "@/components/blocks";
${imports.join("\n")}${blocks.some((b) => b.type === "detail" && b.actions.some((a) => a.action.kind === "toast")) ? '\nimport { toast } from "sonner";' : ""}

export default async function ${pascal(s.title)}Page() {
  return (
    <Screen title=${js(s.title)} layout=${js(s.layout)} audience=${js(s.audience)}>
      <Screen.Main>
${s.regions.main.map((b) => blockJsx(b, bp, "        ")).join("\n")}
      </Screen.Main>${s.regions.side.length ? `\n      <Screen.Side>\n${s.regions.side.map((b) => blockJsx(b, bp, "        ")).join("\n")}\n      </Screen.Side>` : ""}
    </Screen>
  );
}
`;
}

export function entityModule(e: Entity): string {
  const tsType = (t: string) => (t === "number" || t === "money" ? "number" : t === "boolean" ? "boolean" : "string");
  return `// ${e.plural}: ${e.plain}
import { db } from "@/lib/db";

export type ${pascal(e.name)} = {
  id: string;
${e.fields.map((f) => `  ${f.name}: ${f.type === "enum" && f.options ? f.options.map((o) => JSON.stringify(o)).join(" | ") : tsType(f.type)};`).join("\n")}
};

export const ${camel(e.plural)} = db.table<${pascal(e.name)}>(${js(kebab(e.plural).replace(/-/g, "_"))});
export const ${camel(e.name)} = ${camel(e.plural)}.current;
export const create${pascal(e.name)} = ${camel(e.plural)}.insert;

// Sample records used in the Test version (never shipped to Live)
export const sample${pascal(e.plural)}: Partial<${pascal(e.name)}>[] = ${JSON.stringify(e.sample, null, 2)};
`;
}

export function envExample(bp: Blueprint): string {
  const lines = ["# Keys & passwords: never commit real values.", "SUPABASE_URL=", "SUPABASE_PUBLISHABLE_KEY=", "ANTHROPIC_API_KEY="];
  for (const c of bp.connections) {
    if (c.kind === "database") continue;
    if (c.auth === "api_key") lines.push(`${envKey(c.name)}_API_KEY=   # ${c.name}${c.status === "missing" ? " (missing)" : ""}`);
    if (c.auth === "oauth") lines.push(`${envKey(c.name)}_CLIENT_ID=\n${envKey(c.name)}_CLIENT_SECRET=`);
  }
  return lines.join("\n") + "\n";
}

export function generateFiles(bp: Blueprint): GeneratedFile[] {
  const name = kebab(bp.meta.name);
  const files: GeneratedFile[] = [];
  const frameworks = [...new Set(bp.agents.map((a) => a.framework))];

  files.push({
    path: "README.md",
    lang: "md",
    objectRef: { type: "brief", id: "meta" },
    content: `# ${bp.meta.name}

${bp.meta.tagline}

${bp.meta.plain}

## Agents

| Agent | Role | Framework | Supervision |
| --- | --- | --- | --- |
${bp.agents.map((a) => `| ${a.name} | ${a.role} | ${FRAMEWORKS[a.framework].label} | ${a.supervision} |`).join("\n")}

## Run it

\`\`\`sh
cp .env.example .env.local   # add your keys
npm install
npm run dev                  # app on :3000
\`\`\`

Each agent's rehearsals (test conversations) live in its \`agent.yaml\`. Prod AI replays them before every change it opens.

Built with Prod AI. \`blueprint.json\` is the source of truth; edit code or blueprint, both stay in sync.
`,
  });
  files.push({
    path: "package.json",
    lang: "json",
    content: JSON.stringify(
      {
        name,
        private: true,
        scripts: { dev: "next dev", build: "next build", start: "next start", typecheck: "tsc --noEmit" },
        dependencies: { next: "^16.3.0", react: "^19.2.0", "@supabase/ssr": "^0.12.0", ai: "^7.0.0", "@ai-sdk/anthropic": "^4.0.0", "@prodai/blocks": "^2.0.0", ...(frameworks.includes("mastra") ? { "@mastra/core": "^1.0.0" } : {}) },
        devDependencies: { typescript: "^5.9.0" },
      },
      null,
      2,
    ) + "\n",
  });
  files.push({ path: ".env.example", lang: "env", content: envExample(bp) });
  files.push({
    path: "docker-compose.yml",
    lang: "yaml",
    content: `# Run the whole app inside your own VPC. Prod Cloud is optional.
services:
  web:
    build: .
    ports: ["3000:3000"]
    env_file: .env.local
    depends_on: [db, agents]
  agents:
    image: ghcr.io/prodai/agent-runtime:2
    environment:
      AGENTS_DIR: /agents
      REGION: ${bp.meta.region}
    volumes: ["./agents:/agents:ro"]
    env_file: .env.local
  db:
    image: supabase/postgres:17.6.1
    volumes: ["pgdata:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?set in .env.local}
volumes:
  pgdata: {}
`,
  });
  files.push({ path: "blueprint.json", lang: "json", objectRef: { type: "brief", id: "meta" }, content: JSON.stringify({ ...bp, estimate: undefined }, null, 2) + "\n" });
  files.push({
    path: "app/layout.tsx",
    lang: "tsx",
    content: `import { AppShell } from "@/components/blocks";
import { requireSignIn } from "@/lib/auth";

export const metadata = { title: ${js(bp.meta.name)}, description: ${js(bp.meta.tagline)} };

const nav = ${JSON.stringify(bp.screens.map((s) => ({ href: `/${s.slug}`, label: s.title, icon: s.icon, audience: s.audience })), null, 2).replace(/\n/g, "\n")};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  ${bp.meta.auth.enabled ? `await requireSignIn({ providers: ${js(bp.meta.auth.providers)} });` : "// Sign-in is off: anyone with the link can open this app."}
  return (
    <html lang="en">
      <body>
        <AppShell name=${js(bp.meta.name)} nav={nav} theme={${js(bp.meta.theme)}}>{children}</AppShell>
      </body>
    </html>
  );
}
`,
  });
  files.push({ path: "components/blocks/index.ts", lang: "ts", content: `// Prod AI's block library. Every block is a normal React component. Swap any of them for your own.\nexport * from "@prodai/blocks";\n` });
  files.push({ path: "supabase/schema.sql", lang: "sql", content: schemaSql(bp) });
  files.push({
    path: ".github/workflows/checks.yml",
    lang: "yaml",
    content: `# Type-checks and builds every pull request. Agent rehearsals run in Prod AI before it opens one.
name: Checks
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
`,
  });

  for (const s of bp.screens) files.push({ path: `app/(app)/${s.slug}/page.tsx`, lang: "tsx", content: screenPage(s, bp), objectRef: { type: "screen", id: s.id } });
  for (const e of bp.entities) files.push({ path: `lib/data/${e.id}.ts`, lang: "ts", content: entityModule(e), objectRef: { type: "entity", id: e.id } });
  for (const a of bp.agents) {
    const fw = FRAMEWORKS[a.framework];
    const ref = { type: "agent" as const, id: a.id };
    files.push({ path: `agents/${a.id}/agent.yaml`, lang: "yaml", content: agentYaml(a, bp), objectRef: ref });
    files.push({ path: `agents/${a.id}/SOUL.md`, lang: "md", content: soulMd(a), objectRef: ref });
    files.push({ path: `agents/${a.id}/RULES.md`, lang: "md", content: rulesMd(a, bp), objectRef: ref });
    files.push({ path: `agents/${a.id}/DUTIES.md`, lang: "md", content: dutiesMd(a, bp), objectRef: ref });
    files.push({ path: `agents/${a.id}/${fw.fileName(a)}`, lang: fw.language === "python" ? "py" : "ts", content: fw.render(a, bp), objectRef: ref });
  }
  return files;
}

export function filesFor(bp: Blueprint, ref: { type: string; id: string }): GeneratedFile[] {
  const files = generateFiles(bp).filter((f) => f.objectRef && f.objectRef.type === ref.type && f.objectRef.id === ref.id);
  const agent = ref.type === "agent" ? bp.agents.find((a) => a.id === ref.id) : undefined;
  if (agent?.origin !== "imported") return files;
  // An imported agent's code is the owner's. Show the thin wrapper Prod AI adds, never a rewrite of it.
  const runtime = `agents/${agent.id}/${FRAMEWORKS[agent.framework].fileName(agent)}`;
  return files.map((f) => (f.path === runtime ? wrapperFile(agent, null, `agents/${agent.id}`) : f));
}

// ── Imported repositories: the first pull request ───────────────────────────

export type HeldBackFile = { path: string; rule: string; note: string };
export type ImportPullRequest = {
  number: 1;
  /** The one new folder everything is added under. Nothing outside it changes. */
  root: string;
  title: string;
  branch: string;
  files: GeneratedFile[];
  /** Files a fresh project would get that this pull request leaves out, and the signed rule that says so. */
  heldBack: HeldBackFile[];
};
export type ImportContext = {
  repo: { owner: string; name: string };
  /** Every file path in the repository (empty while it loads). */
  repoPaths: string[];
  houseRules: string[];
  frameworks: { id: string; label: string; evidence: string }[];
  /** Where each agent read at import is defined (lib/import/agents.ts), when known. */
  agents?: { name: string; file: string; symbol?: string; framework: string }[];
};

/** The file and symbol an imported agent was read from, matched by its name. */
function agentSource(agent: Agent, ctx: ImportContext): { file: string; symbol?: string } | null {
  const hit = ctx.agents?.find((a) => a.name.toLowerCase() === agent.name.toLowerCase());
  return hit ? { file: hit.file, symbol: hit.symbol } : null;
}

const SOURCE_FILE = /\.(py|ts|tsx|js|mjs)$/;
const SOURCE_RANK = ["agents.py", "agent.py", "agents.ts", "agent.ts", "graph.py", "crew.py", "main.py", "index.ts", "app.py", "server.py"];

/** Best guess at the file that defines an imported framework's agents, from the stack report's evidence. */
export function agentSourceGuess(paths: string[], frameworks: ImportContext["frameworks"], frameworkId: string): string | null {
  const f = frameworks.find((x) => x.id === frameworkId) ?? frameworks[0];
  const evidence = [...(f?.evidence ?? "").matchAll(/(?:dependency in|file) ([^\s·]+)/g)].map((m) => m[1]);
  const direct = evidence.find((p) => SOURCE_FILE.test(p));
  if (direct) return direct;
  const dirs = [...new Set(evidence.map((p) => p.split("/").slice(0, -1).join("/")))];
  for (const dir of dirs.length ? dirs : [""]) {
    const inDir = paths.filter((p) => (!dir || p.startsWith(`${dir}/`)) && SOURCE_FILE.test(p) && !/(^|\/)(tests?|node_modules|\.venv|venv|examples?)\//.test(p));
    for (const name of SOURCE_RANK) {
      const hit = inDir.find((p) => p.split("/").pop() === name);
      if (hit) return hit;
    }
  }
  return null;
}

/** A thin wrapper that loads an imported agent as it is and adds Prod AI's rules around it. `dir` is where it lives. */
function wrapperFile(agent: Agent, source: string | null, dir: string, symbol?: string): GeneratedFile {
  const fw = FRAMEWORKS[agent.framework];
  const ts = source ? /\.(ts|tsx|js|mjs)$/.test(source) : fw.language === "typescript";
  const where = source ?? "your repository";
  const up = "../".repeat(dir.split("/").filter(Boolean).length);
  if (ts) {
    const exportName = symbol ?? `${camel(agent.name.replace(/\bagent\b/i, ""))}Agent`;
    const rel = source ? `${up}${source.replace(/\.(ts|tsx|js|mjs)$/, "")}` : `${up}src/agents`;
    return {
      path: `${dir}/wrapper.ts`,
      lang: "ts",
      objectRef: { type: "agent", id: agent.id },
      content: `// Prod AI wrapper for ${agent.name} (${fw.label}).
// Your agent is not rewritten: it is imported from ${where} exactly as it is.
// This file only adds what Prod AI manages around it: the rules in RULES.md,
// approval gates on irreversible tools, the audit log and rehearsals.
// Delete this wrapper and your agent runs exactly as it did before.
import { wrap } from "@prodai/agents";
${symbol ? `// "${exportName}" is where Prod AI read this agent at import.` : `// Rename "${exportName}" if the agent has a different name in that file.`}
import { ${exportName} as existing } from ${js(rel)};

export const agent = wrap(existing, { spec: new URL("./agent.yaml", import.meta.url) });
`,
    };
  }
  const attr = symbol ?? snakeName(agent.name);
  return {
    path: `${dir}/wrapper.py`,
    lang: "py",
    objectRef: { type: "agent", id: agent.id },
    content: `"""
Prod AI wrapper for ${agent.name.replace(/"/g, "'")} (${fw.label}).

Your agent is not rewritten: it is loaded from ${where} exactly as it is.
This file only adds what Prod AI manages around it: the rules in RULES.md,
approval gates on irreversible tools, the audit log and rehearsals.
Delete this wrapper and your agent runs exactly as it did before.
"""
from pathlib import Path

from prodai import load_existing, wrap  # pip install prodai

SPEC = Path(__file__).with_name("agent.yaml")

# Your existing agent, unchanged. ${symbol ? `"${attr}" is where Prod AI read it at import.` : `Rename "${attr}" if it has a different name in that file.`}
existing = load_existing(${js(source ?? "path/to/your_agent.py")}, attr=${js(attr)})

agent = wrap(existing, spec=SPEC)
`,
  };
}

const snakeName = (name: string) => {
  const base = kebab(name).replace(/-/g, "_") || "agent";
  return /(^|_)agent$/.test(base) ? base : `${base}_agent`;
};

function prReadme(bp: Blueprint, ctx: ImportContext, root: string, files: GeneratedFile[], heldBack: HeldBackFile[]): string {
  const byRule = new Map<string, string[]>();
  for (const h of heldBack) byRule.set(h.rule, [...(byRule.get(h.rule) ?? []), h.path]);
  return `# Prod AI for ${ctx.repo.owner}/${ctx.repo.name}

Proposed in pull request #1. Not merged.

Everything Prod AI adds lives in this \`${root}/\` folder. No existing file in the repository is changed, moved or deleted.

- \`blueprint.json\`: the plan Prod AI mapped from this repository (${bp.screens.length} screens, ${bp.agents.length} agents, ${bp.entities.length} data types).
- \`agents/<id>/\`: one folder per agent with its spec (\`agent.yaml\`), guardrails (\`RULES.md\`), duties and persona${bp.agents.some((a) => a.origin === "imported") ? ", and a thin wrapper around your existing agent code" : ""}.

## House Rules this pull request follows

${ctx.houseRules.length ? ctx.houseRules.map((r) => `- ${r}`).join("\n") : "- None signed."}
${
  byRule.size
    ? `
## Left out on purpose

${[...byRule].map(([rule, paths]) => `- ${rule}\n${paths.map((p) => `  - \`${p}\``).join("\n")}`).join("\n")}
`
    : ""
}
${files.length} new files. Delete this folder and the repository is exactly as it was.
`;
}

/**
 * The first pull request Prod AI would open on an imported repository: only new
 * files, all under one new folder, filtered by the signed House Rules. Agents the
 * rules say to wrap get a thin wrapper instead of a rewrite; CI, infrastructure and
 * a second app scaffold are held back with the rule that holds them.
 */
export function importPullRequest(bp: Blueprint, ctx: ImportContext): ImportPullRequest {
  const policy = houseRulePolicy(ctx.houseRules);
  const existing = new Set(ctx.repoPaths);
  const hasDir = (dir: string) => ctx.repoPaths.some((p) => p.startsWith(`${dir}/`));
  const root = ["prodai", ".prodai", "prodai-studio"].find((d) => !existing.has(d) && !hasDir(d)) ?? "prodai-studio";
  const files: GeneratedFile[] = [];
  const heldBack: HeldBackFile[] = [];
  const hold = (path: string, rule: string, note: string) => heldBack.push({ path, rule, note });
  const add = (f: GeneratedFile, original: string) => {
    const blocked = ruleBlocking(policy, f.path);
    if (blocked) return hold(original, blocked, "A signed House Rule keeps Prod AI out of this path.");
    if (existing.has(f.path)) return hold(original, "Already in your repository.", "Prod AI adds files. It never overwrites yours.");
    files.push(f);
  };
  const runtimeFile = (f: GeneratedFile) => {
    if (f.objectRef?.type !== "agent") return null;
    const agent = bp.agents.find((a) => a.id === f.objectRef!.id);
    return agent && f.path === `agents/${agent.id}/${FRAMEWORKS[agent.framework].fileName(agent)}` ? agent : null;
  };

  for (const f of generateFiles(bp)) {
    const agent = runtimeFile(f);
    if (f.path === "README.md") continue; // replaced by the pull request's own README below
    if (f.path.startsWith(".github/")) {
      // CI only runs from .github/workflows, so it's the one file that can't live in the new folder.
      add({ ...f, path: ".github/workflows/prodai-checks.yml" }, f.path);
    } else if (isInfraPath(f.path) && policy.infra) {
      hold(f.path, policy.infra, "Infrastructure stays yours.");
    } else if ((/^(app|components|lib)\//.test(f.path) || f.path === "package.json") && policy.keepFramework) {
      hold(f.path, policy.keepFramework, "Screens would add a second app next to yours. They wait until you choose where they live.");
    } else if (agent && agent.origin === "imported" && policy.wrapAgents) {
      hold(f.path, policy.wrapAgents, "Your agent code stays as it is. A thin wrapper is proposed instead.");
      const src = agentSource(agent, ctx);
      add(wrapperFile(agent, src?.file ?? agentSourceGuess(ctx.repoPaths, ctx.frameworks, agent.framework), `${root}/agents/${agent.id}`, src?.symbol), f.path);
    } else {
      add({ ...f, path: `${root}/${f.path}` }, f.path);
    }
  }
  const readme: GeneratedFile = { path: `${root}/README.md`, lang: "md", objectRef: { type: "brief", id: "meta" }, content: "" };
  files.unshift(readme);
  readme.content = prReadme(bp, ctx, root, files, heldBack);
  return {
    number: 1,
    root,
    title: `Add Prod AI specs${bp.agents.some((a) => a.origin === "imported") ? " and agent wrappers" : ""} in ${root}/`,
    branch: "prodai/adopt",
    files,
    heldBack,
  };
}
